// <auto-generated />
using System;
using IettSeferSistemi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IettSeferSistemi.Infrastructure.Migrations
{
    [DbContext(typeof(IettDbContext))]
    [Migration("20250815112803_AddActiveFieldToKullanici")]
    partial class AddActiveFieldToKullanici
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.BakimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BakimTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Maliyet")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OtobusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OtobusId");

                    b.ToTable("BakimKayitlari");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Hat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaslangicDuragi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BitisDuragi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurakSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("HatKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MesafeKm")
                        .HasColumnType("float");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("TahminSureDakika")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hatlar");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Otobus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Otobusler");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Sefer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<double>("GidilenMesafeKm")
                        .HasColumnType("float");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KalkisZamani")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OtobusId")
                        .HasColumnType("int");

                    b.Property<int>("SoforId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VarisZamani")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HatId");

                    b.HasIndex("OtobusId");

                    b.HasIndex("SoforId");

                    b.ToTable("Seferler");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.SistemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("SistemLoglari");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.YakitTuketim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("Litre")
                        .HasColumnType("float");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("OtobusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OtobusId");

                    b.ToTable("YakitTuketimleri");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.YolcuSayim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeferId")
                        .HasColumnType("int");

                    b.Property<int>("YolcuSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeferId");

                    b.ToTable("YolcuSayimlari");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.BakimKaydi", b =>
                {
                    b.HasOne("IettSeferSistemi.Domain.Entities.Otobus", "Otobus")
                        .WithMany("BakimKayitlari")
                        .HasForeignKey("OtobusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otobus");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Sefer", b =>
                {
                    b.HasOne("IettSeferSistemi.Domain.Entities.Hat", "Hat")
                        .WithMany("Seferler")
                        .HasForeignKey("HatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IettSeferSistemi.Domain.Entities.Otobus", "Otobus")
                        .WithMany("Seferler")
                        .HasForeignKey("OtobusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IettSeferSistemi.Domain.Entities.Kullanici", "Sofor")
                        .WithMany("Seferler")
                        .HasForeignKey("SoforId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hat");

                    b.Navigation("Otobus");

                    b.Navigation("Sofor");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.SistemLog", b =>
                {
                    b.HasOne("IettSeferSistemi.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany("Loglar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.YakitTuketim", b =>
                {
                    b.HasOne("IettSeferSistemi.Domain.Entities.Otobus", "Otobus")
                        .WithMany("YakitTuketimleri")
                        .HasForeignKey("OtobusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Otobus");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.YolcuSayim", b =>
                {
                    b.HasOne("IettSeferSistemi.Domain.Entities.Sefer", "Sefer")
                        .WithMany("YolcuSayimlari")
                        .HasForeignKey("SeferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sefer");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Hat", b =>
                {
                    b.Navigation("Seferler");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Kullanici", b =>
                {
                    b.Navigation("Loglar");

                    b.Navigation("Seferler");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Otobus", b =>
                {
                    b.Navigation("BakimKayitlari");

                    b.Navigation("Seferler");

                    b.Navigation("YakitTuketimleri");
                });

            modelBuilder.Entity("IettSeferSistemi.Domain.Entities.Sefer", b =>
                {
                    b.Navigation("YolcuSayimlari");
                });
#pragma warning restore 612, 618
        }
    }
}
